To reproduce the bug
* Run ./initialize-python-env.sh to generate client and initialize python env
* Run python test.py using the virtual environment ".python_env" created by previous script